
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sejhzvuogqskidbjtbvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlamh6dnVvZ3Fza2lkYmp0YnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjQ1MDksImV4cCI6MjA2MjAwMDUwOX0.3yOnuPKc3RhPNRMbHC1iyZ9yn6neK_CKj3Iq92bgfPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
