
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sejhzvuogqskidbjtbvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlamh6dnVvZ3Fza2lkYmp0YnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjQ1MDksImV4cCI6MjA2MjAwMDUwOX0.3yOnuPKc3RhPNRMbHC1iyZ9yn6neK_CKj3Iq92bgfPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define extended database types
interface CustomDatabase extends Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          is_farmer: boolean;
          farm_name?: string;
        }
        Insert: {
          id: string;
          first_name: string;
          last_name: string;
          is_farmer: boolean;
          farm_name?: string;
        }
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          is_farmer?: boolean;
          farm_name?: string;
        }
      }
    } & Database['public']['Tables']
    Views: Database['public']['Views']
    Functions: Database['public']['Functions']
    Enums: Database['public']['Enums']
    CompositeTypes: Database['public']['CompositeTypes']
  }
}

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
